services:
  ingress:
    build: ./ingress
    container_name: ingress
    ports:
      - "8080:80"
    depends_on:
      - persist
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./ingress/default.conf:/etc/nginx/conf.d/default.conf

  persist:
    build: ./persist
    container_name: persist
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
