services:
  ingress:
    build: ./ingress
    container_name: ingress
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - persist
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./ingress/default.conf:/etc/nginx/conf.d/default.conf
      - ./ingress/certificates/acmecorp.com.key:/etc/nginx/ssl/server.key
      - ./ingress/certificates/acmecorp.com.crt:/etc/nginx/ssl/server.crt

  persist:
    build: ./persist
    container_name: persist
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
