apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: persist-secret
    type: Opaque
    files:
      - config.yaml

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
